language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cppcheck

before_script:
    - gem install pdd
    - ./style.sh

script:
    - cmake .
    - make VERBOSE=1
    - make test
