version: 2.0

dependencies:
  pre:
    sudo apt-get install cmake

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: |
          cmake .
          make all test
