version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: |
          sudo apt-get install cmake cppcheck doxygen
          gem install pdd
          cmake .
          make style
          make all test
      - store_test_results:
          path: shippable/testresults 
