version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: |
          sudo apt-get install cmake cppcheck doxygen python3-pip
          sudo pip3 install cpplint
          gem install pdd
          cmake -DCMAKE_CXX_FLAGS="--coverage" .
          make style
          make VERBOSE=1
          make test
          bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: .
